### ISSUE TITLE
Suggested hardware? (Pi 4/5, RAM, SSD storage, etc.)

### ISSUE THREAD

**Issue by abceleung** [kallyaleksiev/k8s-on-rpi#1]
Hi, I am planning to create a K8s cluster with some x86 machines and raspberry pis, though I haven't bought any Raspberry Pi yet. I am curious about your setup.

Could you share the following:
1. What model(s) of Raspberry Pi are you using?
2. Do you think 2GB of RAM is sufficient for a control plane node?
3. Would SSDs (via USB-to-M.2 adapter or the M.2 HAT for Pi 5) significantly improve the performance for a control plane node?

Thanks!

**Comment by kallyaleksiev** [comment]
hey hey @abceleung ! to answer your questions:

1. I am using one raspberry pi 4 where I'm running the control node and one (occasionally more) Raspberry Pi 5s as workers; 4 cores each, memory is 4GB for pi 4 and 8GB for pi 5
2. It depends on your workload. For smaller workloads it could work. For reference, when you run the full tutorial here you end up with about 1GB usage in total for the control plane I think.
3. Again depends on the workloads you plan to run. If your workloads are i/o heavy or if your cluster is quite dynamic (e.g. scaling up and down a large number of pods with `emptyDir` backed by disk storage) then SSDs could be beneficial (over SD cards)

**Comment by abceleung** [comment]
> hey hey @abceleung ! to answer your questions:
> 
>     1. I am using one raspberry pi 4 where I'm running the control node and one (occasionally more) Raspberry Pi 5s as workers; 4 cores each, memory is 4GB for pi 4 and 8GB for pi 5
> 
>     2. It depends on your workload. For smaller workloads it could work. For reference, when you run the full tutorial here you end up with about 1GB usage in total for the control plane I think.
> 
>     3. Again depends on the workloads you plan to run. If your workloads are i/o heavy or if your cluster is quite dynamic (e.g. scaling up and down a large number of pods with `emptyDir` backed by disk storage) then SSDs could be beneficial (over SD cards)

Thanks fro your answer! BTW I think you should write your hardware spec in the guide too.
